// AUTO-GENERATED by demo-reel/capture-editor-glow.mjs — node rects as fractions of editor-clean.png
export const EDITOR_ASPECT = 1.70751;
export const EDITOR_NODES = [
  {
    "type": "promptNode",
    "x": 0.045717592592592594,
    "y": 0.11679515914012321,
    "w": 0.2856979016904478,
    "h": 0.23902161790448215
  },
  {
    "type": "sizeNode",
    "x": 0.045717592592592594,
    "y": 0.5404387462751667,
    "w": 0.22555096944173178,
    "h": 0.3433278200654644
  },
  {
    "type": "generateNode",
    "x": 0.40659915076361763,
    "y": 0.309360398605407,
    "w": 0.180440796746148,
    "h": 0.3180135191664865
  },
  {
    "type": "outputNode",
    "x": 0.6697419484456381,
    "y": 0.19382123984838193,
    "w": 0.28569793701171875,
    "h": 0.35456082189507165
  }
] as const;
